### PR TITLE
WIP: Track GPU usage using DCGM

### PR DESCRIPTION
**Pull request by samcmill**
This is a work in progress merge request to add support for tracking GPU usage.

The NVIDIA Datacenter GPU Manager (DCGM) library is used to detect whether a compute pid was run on each of the GPUs during execution.  DCGM is free to download from https://developer.nvidia.com/data-center-gpu-manager-dcgm.  

Adds `--with-trackGPU` configure option (default=no).  If enabled, then DCGM is added as a dependency and the GPU tracking code is enabled.

Currently, it only prints out the number of GPUs used when tracing is enabled.  I would like to get feedback on the pull request before proceeding further.  Additional changes are still needed to add a `num_gpu` column to the database and propagate the information through to the database.

```
myinit(LD_PRELOAD,/home/smcmillan/peer){
  Test for __XALT_INITIAL_STATE__: "(NULL)", STATE: "LD_PRELOAD"
  Test for XALT_EXECUTABLE_TRACKING: yes
  Test for rank == 0, rank: 0
  GPU tracing
    -> XALT is build to track all programs, Current program is a scalar program -> Not producing a start record
}

WARNING: device 0 cannot directly access device 1
max error: 1.192093e-07
max error: 1.192093e-07

myfini(LD_PRELOAD){
  GPU tracing
  4 GPUs detected
  GPU 0: num compute pids 1
  GPU 1: num compute pids 1
  GPU 2: num compute pids 0
  GPU 3: num compute pids 0
  2 of 4 GPUs were used
    -> Scalar Sampling program run_time: 0.436983: (my_rand: 0.669763 <= prob: 1) for program: /home/smcmillan/peer
  Recording State at end of scalar user program:
    LD_LIBRARY_PATH= PATH=/usr/bin:/bin /tmp/usr/local/xalt/xalt//libexec/xalt_run_submission --interfaceV 3 --ppid 39373 --syshost "psg" --start "1531944271.5779" --end "1531944272.0149" --exec "/home/smcmillan/peer" --ntasks 1 --uuid "81130c8d-9ff4-4319-bdf6-95f73db278ea" --prob 1 --path "/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/sbin:/usr/sbin:/cm/extra/apps/Modules/3.2.10/bin:/home/smcmillan/bin"   -- "/home/smcmillan/peer"
}
```

### CODE REVIEW

**Comment by rtmclay** [comment]
I have merged this in to look at it.  But the main question is that sites might have some nodes with GPU's and some without.  XALT needs to work with the dcgm library installed on nodes that do not have GPU's.

Is this going to be a problem?

**Comment by rtmclay** [comment]
Also the shutdown of the dcgm library needs to work when the memory heap is corrupted.  In other words: are the following necessary when the user program is about to die anyway?

```
      dcgmJobRemove(dcgm_handle, uuid_str);
      dcgmStopEmbedded(dcgm_handle);
      dcgmShutdown();
```

**Comment by samcmill** [comment]
DCGM can be installed on nodes without GPUs.  I would suggest a runtime environment variable to control whether GPU data is collected or not.  `XALT_TRACING_GPU`?  The XALT environment module on the GPU / non-GPU nodes could set it accordingly.

The shutdown calls are not strictly necessary since the process it about to die anyway, but are good practice to include, I think.  Are you concerned that the calls may hang?

**Comment by rtmclay** [comment]
Using an env. var. is a help.  But we have clusters where some nodes have GPUs and other nodes don't.  The env. var. XALT_TRACING_GPU would most like have to set for all jobs whether or not they had GPUs.  The reason is that at least in our case, all environment vars are set on the login nodes and then jobs are submitted to the job scheduler.  

As to the shutdown calls, I worry about unnecessary error messages.  Also can the DCGM calls be executed on non-GPU nodes?

**Comment by rtmclay** [comment]
On branch 2.1.2-gpu, I have checked-in a working version version of XALT that has the num_gpus going into the database.  On all systems except those with GPU and the DCGM library installed, this number will be zero.  

Please test this branch at your systems with GPUs and the DCGM library to see if this works when there are GPUs.  Please also test where the DCGM library is installed but it is run on a system with no GPUs.
  
Thanks for the patch.

**Comment by samcmill** [comment]
I've tested branch 2.1.2-gpu on a system without GPUs but with GPU tracking enabled (`--with-trackGPU=yes`).  DCGM installs without issues.  XALT builds fine (but see below).  Setting `XALT_GPU_TRACKING=yes`, I see the following:

```
myinit(LD_PRELOAD,/opt/hello){
  Test for __XALT_INITIAL_STATE__: "(NULL)", STATE: "LD_PRELOAD"
  Test for XALT_EXECUTABLE_TRACKING: yes
  Test for rank == 0, rank: 0
  GPU tracing
Error: Failed to initialize NVML
    -> Quitting => Cannot start DCGM: DCGM initialization error
}

Hello world!

myfini(LD_PRELOAD){
    -> Scalar Sampling program run_time: 1.53236e+09: (my_rand: 0.847773 <= prob: 1) for program: /opt/hello
  Recording State at end of scalar user program:
    LD_LIBRARY_PATH= PATH=/usr/bin:/bin /usr/local/xalt/xalt//libexec/xalt_run_submission --interfaceV 4 --ppid 0 --syshost "psg" --start "0.0000" --end "1532357725.4375" --exec "/opt/hello" --ntasks 1 --uuid "c8a5a864-1831-4487-ad3e-b583a17efb36" --prob 1 --ngpus 0 (null) (null) -- ["/opt/hello"]
}
```

I don't know if instead of "quitting" the tracing should continue with GPU tracking disabled?

A few notes:

1. `USE_DCGM` is not getting defined properly.  I had to insert `#define USE_DCGM 1` in `xalt_initialize.c`.  It looks like you reverted the `CPPFLAGS_DCGM` change I made to `src/Makefile.in`?

2. I suggest modifying `myfini()` as follows to better handle the case where GPU tracking is not available.  There were no complaints in the output without this additional check.

```
@@ -676,7 +677,7 @@ void myfini()
   unsetenv("LD_PRELOAD");
 
 #ifdef USE_DCGM
-  if (xalt_gpu_tracking)
+  if (xalt_gpu_tracking && dcgm_handle != NULL)
     {
       /* Collect DCGM job stats */
       dcgmReturn_t result;
```

**Comment by rtmclay** [comment]
Thanks for the bug report.  Yes, I remove CPPFLAGS_DCGM because it can be handled by a header file that autoconf handles.  The trouble was that I didn't do it correctly.  I believe that I have done so this time but please check me.

**********************************************************************************************************
HOWEVER, I think that we have a problem.  Looking at the output you reported.  You are getting a message:
```
Error: Failed to initialize NVML
```
That is not coming from xalt_initialize.c.  It looks like it is coming from the dcgmInit() call.  That can't happen.  Users will freak out and complain that they get this error message when there is nothing wrong with their program.  It will happen if XALT is built with GPU tracking support and their program is run on a node that doesn't have GPU's.  

Is there a way to tell dcgmInit() to be quiet if there is no GPU?  If there isn't then I don't see how this can be used.

**********************************************************************************************************************

Please test the latest version on this branch and let me know about how to get dcgmInit() to be quiet.

**Comment by samcmill** [comment]
`USE_DCGM` is set correctly now.

The output is coming from `dcgmStartEmbedded`.  

I've filed an enhancement request with the DCGM team for any option to suppress any output.  In the meantime, here's a crude workaround:

```
diff --git a/src/xalt_initialize.c b/src/xalt_initialize.c
index 30ad547..733fd77 100644
--- a/src/xalt_initialize.c
+++ b/src/xalt_initialize.c
@@ -39,6 +39,7 @@
 #include <errno.h>
 #include <sys/utsname.h>
 #include <unistd.h>
+#include <fcntl.h>
 #ifdef __MACH__
 #  include <libproc.h>
 #endif
@@ -157,6 +158,23 @@ static char *       ldLibPathArg          = NULL;
 static int num_gpus                       = 0;
 #ifdef USE_DCGM
 static dcgmHandle_t dcgm_handle           = NULL;
+
+/* Temporarily disable any stderr messages from DCGM */
+#define DCGMFUNC2(FUNC,x1,x2,out)    \
+{                                    \
+  dcgmReturn_t __result;             \
+  int fd1, fd2;                      \
+  fflush(stderr);                    \
+  fd1 = dup(STDERR_FILENO);          \
+  fd2 = open("/dev/null", O_WRONLY); \
+  dup2(fd2, STDERR_FILENO);          \
+  close(fd2);                        \
+  __result = FUNC(x1, x2);           \
+  fflush(stderr);                    \
+  dup2(fd1, STDERR_FILENO);          \
+  close(fd1);                        \
+  (*(out)) = __result;               \
+}
 #endif
 
 #define HERE fprintf(stderr, "%s:%d\n",__FILE__,__LINE__)
@@ -464,7 +482,7 @@ void myinit(int argc, char **argv)
           return;
         }
 
-      result = dcgmStartEmbedded(DCGM_OPERATION_MODE_MANUAL, &dcgm_handle);
+      DCGMFUNC2(dcgmStartEmbedded, DCGM_OPERATION_MODE_MANUAL, &dcgm_handle, &result);
       if (result != DCGM_ST_OK)
         {
           DEBUG1(stderr, "    -> Stopping GPU Tracking => Cannot start DCGM: %s\n}\n\n", errorString(result));
```

With this, the output becomes:

```
myinit(LD_PRELOAD,/opt/hello){
  Test for __XALT_INITIAL_STATE__: "(NULL)", STATE: "LD_PRELOAD"
  Test for XALT_EXECUTABLE_TRACKING: yes
  Test for rank == 0, rank: 0
  GPU tracing
    -> Stopping GPU Tracking => Cannot start DCGM: DCGM initialization error
}

Hello world!

myfini(LD_PRELOAD){
    -> Scalar Sampling program run_time: 1.53238e+09: (my_rand: 0.959834 <= prob: 1) for program: /opt/hello
  Recording State at end of scalar user program:
    LD_LIBRARY_PATH= PATH=/usr/bin:/bin /usr/local/xalt/xalt//libexec/xalt_run_submission --interfaceV 4 --ppid 0 --syshost "psg" --start "0.0000" --end "1532382898.1045" --exec "/opt/hello" --ntasks 1 --uuid "94b7d199-a4e7-4a80-9ec2-9fc27121991e" --prob 1 --ngpus 0 (null) (null) -- ["/opt/hello"]
}
``

**Comment by rtmclay** [comment]
O.K.  please try the latest update on this branch to see how well this works.  It would be useful to know how expensive the DCGMFUNC2() macro is costing.  If you could, please test the timing with and without the DCGMFUNC2().  Thanks!

**Comment by samcmill** [comment]
Average time for `dcgmStartEmbedded()` on a system with GPUs over 20 runs:

```
w/  DCGMFUNC2()    0.1004 seconds (max 0.1034 seconds)
w/o DCGMFUNC2()    0.1019 seconds (max 0.1036 seconds)
```

So the macro cost is negligible.

Everything looks find on the data collection side.  However, there may be issues transmitting the data to the database?  I built with `--with-transmission=file` and the json output files look truncated?

```
[smcmillan@hsw223 xalt]$ ~/peer 
...
myinit(LD_PRELOAD,/home/smcmillan/peer){
  Test for __XALT_INITIAL_STATE__: "(NULL)", STATE: "LD_PRELOAD"
  Test for XALT_EXECUTABLE_TRACKING: yes
  Test for rank == 0, rank: 0
  GPU tracing
    -> XALT is build to track all programs, Current program is a scalar program -> Not producing a start record
}

WARNING: device 0 cannot directly access device 1
max error: 1.192093e-07
max error: 1.192093e-07

myfini(LD_PRELOAD){
  GPU tracing
  4 GPUs detected
  GPU 0: num compute pids 1
  GPU 1: num compute pids 1
  GPU 2: num compute pids 0
  GPU 3: num compute pids 0
  2 of 4 GPUs were used
    -> Scalar Sampling program run_time: 0.432843: (my_rand: 0.138768 <= prob: 1) for program: /home/smcmillan/peer
  Recording State at end of scalar user program:
    LD_LIBRARY_PATH= PATH=/usr/bin:/bin /tmp/usr/local/xalt/xalt//libexec/xalt_run_submission --interfaceV 4 --ppid 43248 --syshost "psg" --start "1532443743.0868" --end "1532443743.5197" --exec "/home/smcmillan/peer" --ntasks 1 --uuid "2b2bd161-0cea-4ac5-8e30-2718b3f37537" --prob 1 --ngpus 2 --path "/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/sbin:/usr/sbin:/cm/extra/apps/Modules/3.2.10/bin:/home/smcmillan/bin"   -- ["/home/smcmillan/peer"]
}

[smcmillan@hsw223 xalt]$ export XALT_TRACING=no
[smcmillan@hsw223 xalt]$ cat ~/.xalt.d/run.psg.2018_07_24_07_49_03_0868.zzz.2b2bd161-0cea-4ac5-8e30-2718b3f37537.json 
{"cmdlineA":["/home/smcmillan/peer"]A
```

**Comment by rtmclay** [comment]
You are correct.  The json string you are seeing is indeed truncated but I'm not reproducing it.  I get a full string.  It is not clear why this is happening.  I have updated this branch to allow xalt_run_submission to write to stderr when it is called from myfini().  Please try running exactly what you are running above with the updated version of XALT. Maybe the current level of debugging will tell us what the problem is.  You might also try running a simple  hello world program (w/o gpu usage) to see what json is generated. 

Please let me know what output you get from both your "peer" program and a simple hello world program.  From there it should be possible to add more debugging to find where things are going wrong.  Thanks!

**Comment by samcmill** [comment]
Updated the latest version of the branch.

Tried 3 different combinations
1. `--with-trackGPU=no`
2. `--with-trackGPU=yes` and `XALT_GPU_TRACKING=no`
3. `--with-trackGPU=yes` and `XALT_GPU_TRACKING=yes`

In all 3 cases, the `peer` program generates the truncated record.

In all 3 cases, a "Hello World" program generates a complete, but invalid record (note the "nknown" following the "cmdlineA" value):

```
{"cmdlineA":["/home/smcmillan/hello"]nknown,"ptA":[{"cmd_name":"bash","cmd_path":"/usr/bin/bash","pid":8273,"cmdlineA":["/usr/bin/bash","-i"]}],"envT":{...},"userT":"account":"unknown","submit_host":"psgcluster","queue":"unknown","currentEpoch":"1532465028.753395","syshost":"psg","exec_type":"binary","run_uuid":"8c4d60a2-3a36-4e44-b7dc-0a099c99d08f","start_date":"Tue Jul 24 13:43:48 2018","user":"smcmillan","exec_path":"/home/smcmillan/hello","cwd":"/home/smcmillan/git/external/xalt","execModify":"Tue Jul 24 13:41:55 2018","job_id":"8242"},"userDT":{"num_nodes":1.000000,"start_time":1532465028.742300,"end_time":1532465028.742400,"run_time":0.000100,"num_tasks":1.000000,"num_threads":1.000000,"probability":1.000000,"num_gpus":0.000000,"currentEpoch":1532465028.753395,"exec_epoch":1532464915.000000,"num_cores":1.000000},"xaltLinkT":{},"hash_id":"ed0028b4a8196ce18c8a97064453b4dccc7b413a","libA":[["/lib64/libc.so.6","0"]],"XALT_measureT":{"07____total_____":0.011714,"02_Sha1_exec____":0.000255,"06_ParseLDD_ldd_":0.007302,"01_BuildUserT___":0.000138,"05_ExtractXALTR_":0.003681,"06_ParseLDD_sha1":0.000009,"03_BuildEnvT____":0.000185,"04_WalkProcTree_":0.000105}}
```

Corresponding TRACING output:
```
myinit(LD_PRELOAD,/home/smcmillan/hello){
  Test for __XALT_INITIAL_STATE__: "(NULL)", STATE: "LD_PRELOAD"
  Test for XALT_EXECUTABLE_TRACKING: yes
  Test for rank == 0, rank: 0
    -> XALT is build to track all programs, Current program is a scalar program -> Not producing a start record
}

Hello World!

myfini(LD_PRELOAD){
    -> Scalar Sampling program run_time: 4.50611e-05: (my_rand: 0.808832 <= prob: 1) for program: /home/smcmillan/hello
  Recording State at end of scalar user program:
    LD_LIBRARY_PATH= PATH=/usr/bin:/bin /tmp/usr/local/xalt/xalt//libexec/xalt_run_submission --interfaceV 4 --ppid 8273 --syshost "psg" --start "1532465028.7423" --end "1532465028.7424" --exec "/home/smcmillan/hello" --ntasks 1 --uuid "8c4d60a2-3a36-4e44-b7dc-0a099c99d08f" --prob 1 --ngpus 0 --path "/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/sbin:/usr/sbin:/cm/extra/apps/Modules/3.2.10/bin:/home/smcmillan/bin"   -- ["/home/smcmillan/hello"]
}


xalt_run_submission(zzz) {
  Built envT
  Extracted recordT from executable
  Built userT, userDT
  Filter envT
  Parsed LDD
  Using XALT_TRANSMISSION_STYLE: file
  Built json string
  Wrote json run file : /home/smcmillan/.xalt.d/run.psg.2018_07_24_13_43_48_7423.zzz.8c4d60a2-3a36-4e44-b7dc-0a099c99d08f.json
}
```

**Comment by rtmclay** [comment]
I have found a bug with the base64_decode() routine which failed to add a null termination.  This can explain the problem you found with the hello_world program.  It might explain the problem with peer.  Would you please test: 

- the updated version on this branch to see if fixes the problem you saw hello

- Please test the gpu program on with XALT_TRACING=yes so that we can see what is going on with that.

Thanks!

**Comment by samcmill** [comment]
The latest branch fixes the issues with both the peer and hello programs.  Both are recorded correctly with valid json files.  

Looks good to me!

**Comment by rtmclay** [comment]
I have merged this branch on the master branch and release XALT 2.2 with all the changes we made on this branch.  Thanks very much for working with me on getting this new capability added into XALT!

**Pull request merged**
